"""empty message

Revision ID: 06b0f36f9fa8
Revises: b7240663b354
Create Date: 2022-02-12 14:30:35.152498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b0f36f9fa8'
down_revision = 'b7240663b354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'image')
    # ### end Alembic commands ###
