"""empty message

Revision ID: 329e211ea498
Revises: cdd3017655e0
Create Date: 2022-02-09 13:51:16.709323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329e211ea498'
down_revision = 'cdd3017655e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'characteristic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('game', 'text_challenger',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'text_challenger',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('game', 'characteristic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
