"""empty message

Revision ID: 329ea9f47f2f
Revises: 000abb0a1040
Create Date: 2022-02-04 15:03:02.754272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329ea9f47f2f'
down_revision = '000abb0a1040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('challenger_id', sa.Integer(), nullable=False))
    op.add_column('game', sa.Column('responder_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game', 'player', ['responder_id'], ['player_id'])
    op.create_foreign_key(None, 'game', 'player', ['challenger_id'], ['player_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'responder_id')
    op.drop_column('game', 'challenger_id')
    # ### end Alembic commands ###
