"""empty message

Revision ID: b7240663b354
Revises: 329e211ea498
Create Date: 2022-02-09 14:08:21.419280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7240663b354'
down_revision = '329e211ea498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'text_challenger',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'text_challenger',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
