"""empty message

Revision ID: be485eff3258
Revises: 6d296991c85a
Create Date: 2022-01-30 11:02:56.497681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be485eff3258'
down_revision = '6d296991c85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'rating_count')
    # ### end Alembic commands ###
