"""empty message

Revision ID: cdd3017655e0
Revises: dced63cf5873
Create Date: 2022-02-09 10:29:01.289269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd3017655e0'
down_revision = 'dced63cf5873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('characteristic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'characteristic')
    # ### end Alembic commands ###
