"""empty message

Revision ID: dced63cf5873
Revises: 
Create Date: 2022-02-08 17:37:25.562327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dced63cf5873'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('text_challenger', sa.String(), nullable=True),
    sa.Column('challenger_id', sa.Integer(), nullable=True),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenger_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('player')
    # ### end Alembic commands ###
